/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinix.amphibia.components;

import com.equinix.amphibia.Amphibia;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author dgofman
 */
public class TransferDialog extends javax.swing.JPanel {
    
    private JDialog dialog;
    private final MainPanel mainPanel;
    private final DefaultComboBoxModel targetModel;
    private final DefaultComboBoxModel schemaModel;
    
    public final DefaultMutableTreeNode treeNode;
    public final DefaultTreeModel treeModel;

    /**
     * Creates new form TransferDialog
     */
    public TransferDialog(MainPanel mainPanel) {
        this.mainPanel = mainPanel;
        
        targetModel = new DefaultComboBoxModel();
        schemaModel = new DefaultComboBoxModel();
        
        treeNode = new DefaultMutableTreeNode();
        treeModel = new DefaultTreeModel(treeNode);
        
        initComponents();
        
        dialog = Amphibia.createDialog(this, new Object[]{}, false);
        dialog.setSize(new Dimension(610, 430));
        java.awt.EventQueue.invokeLater(() -> {
            dialog.setLocationRelativeTo(mainPanel);
        });
    }

    public void openDialog(TreeCollection collection, Editor.Entry entry) {
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        pnlHeader = new JPanel();
        lblTarget = new JLabel();
        cmbTarget = new JComboBox<>();
        lblPath = new JLabel();
        txtPath = new JTextField();
        lblSchema = new JLabel();
        cmbSchema = new JComboBox<>();
        spnSchema = new JScrollPane();
        treeSchema = new JTree();

        setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
        setLayout(new BorderLayout());

        pnlHeader.setBorder(BorderFactory.createEmptyBorder(1, 1, 5, 1));
        pnlHeader.setLayout(new GridBagLayout());

        lblTarget.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        ResourceBundle bundle = ResourceBundle.getBundle("com/equinix/amphibia/messages"); // NOI18N
        lblTarget.setText(bundle.getString("targetProperty")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(2, 0, 0, 0);
        pnlHeader.add(lblTarget, gridBagConstraints);

        cmbTarget.setModel(this.targetModel);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        pnlHeader.add(cmbTarget, gridBagConstraints);
        cmbTarget.getAccessibleContext().setAccessibleDescription("");

        lblPath.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        lblPath.setText(bundle.getString("propertyPath")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        pnlHeader.add(lblPath, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(5, 0, 5, 0);
        pnlHeader.add(txtPath, gridBagConstraints);

        lblSchema.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        lblSchema.setText(bundle.getString("schemas")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        pnlHeader.add(lblSchema, gridBagConstraints);

        cmbSchema.setModel(this.schemaModel);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        pnlHeader.add(cmbSchema, gridBagConstraints);

        add(pnlHeader, BorderLayout.NORTH);

        treeSchema.setModel(this.treeModel);
        spnSchema.setViewportView(treeSchema);

        add(spnSchema, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JComboBox<String> cmbSchema;
    JComboBox<String> cmbTarget;
    JLabel lblPath;
    JLabel lblSchema;
    JLabel lblTarget;
    JPanel pnlHeader;
    JScrollPane spnSchema;
    JTree treeSchema;
    JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
