/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinix.amphibia.components;

import com.equinix.amphibia.Amphibia;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author dgofman
 */
public class WizardTab extends javax.swing.JPanel {
    
    private ResourceBundle bundle;
    private Wizard wizard;
    private DefaultComboBoxModel interfacesModel;
    
    /**
     * Creates new form WizardTab
     * @param wizard the value of wizard
     */
    public WizardTab(Wizard wizard) {
        this.wizard = wizard;
        
        bundle = Amphibia.getBundle();
        
        interfacesModel = new DefaultComboBoxModel(new String[] {bundle.getString("none")});
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        pnlTop = new JPanel();
        lblEndpoint = new JLabel();
        pnlEndpoint = new JPanel();
        cmdEndpoint = new JComboBox<>();
        btnEndpointInfo = new JButton();
        lblInterface = new JLabel();
        pnlInterface = new JPanel();
        cmdInterface = new JComboBox<>();
        btnInterfaceInfo = new JButton();
        lblMethod = new JLabel();
        pnlMethodURI = new JPanel();
        cmdMethod = new JComboBox<>();
        lblURI = new JLabel();
        lblPath = new JLabel();
        txtPath = new JTextField();
        btnHeaders = new JButton();
        tabBody = new JTabbedPane();
        spnReqBody = new JScrollPane();
        txtReqBody = new JTextArea();
        spnResBody = new JScrollPane();
        txtResBody = new JTextArea();
        spnConsole = new JScrollPane();
        txtConsole = new JTextArea();
        pnlFooter = new JPanel();
        lblStatusCode = new JLabel();
        lblCode = new JLabel();
        btnSend = new JButton();
        btnSave = new JButton();

        setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new BorderLayout());

        pnlTop.setLayout(new GridBagLayout());

        ResourceBundle bundle = ResourceBundle.getBundle("com/equinix/amphibia/messages"); // NOI18N
        lblEndpoint.setText(bundle.getString("endpoint")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        pnlTop.add(lblEndpoint, gridBagConstraints);

        pnlEndpoint.setLayout(new FlowLayout(FlowLayout.LEFT));

        cmdEndpoint.setModel(wizard.sharedEndPointModel);
        cmdEndpoint.setPreferredSize(new Dimension(250, 20));
        cmdEndpoint.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                cmdEndpointItemStateChanged(evt);
            }
        });
        cmdEndpoint.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cmdEndpointActionPerformed(evt);
            }
        });
        pnlEndpoint.add(cmdEndpoint);

        btnEndpointInfo.setIcon(new ImageIcon(getClass().getResource("/com/equinix/amphibia/icons/icon-16-info.png"))); // NOI18N
        btnEndpointInfo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEndpointInfo.setFocusPainted(false);
        btnEndpointInfo.setPreferredSize(new Dimension(30, 22));
        btnEndpointInfo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEndpointInfoActionPerformed(evt);
            }
        });
        pnlEndpoint.add(btnEndpointInfo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        pnlTop.add(pnlEndpoint, gridBagConstraints);

        lblInterface.setText(bundle.getString("interface")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        pnlTop.add(lblInterface, gridBagConstraints);

        pnlInterface.setLayout(new FlowLayout(FlowLayout.LEFT));

        cmdInterface.setPreferredSize(new Dimension(250, 20));
        cmdInterface.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cmdInterfaceActionPerformed(evt);
            }
        });
        pnlInterface.add(cmdInterface);

        btnInterfaceInfo.setIcon(new ImageIcon(getClass().getResource("/com/equinix/amphibia/icons/icon-16-info.png"))); // NOI18N
        btnInterfaceInfo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnInterfaceInfo.setFocusPainted(false);
        btnInterfaceInfo.setPreferredSize(new Dimension(30, 22));
        btnInterfaceInfo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnInterfaceInfoActionPerformed(evt);
            }
        });
        pnlInterface.add(btnInterfaceInfo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        pnlTop.add(pnlInterface, gridBagConstraints);

        lblMethod.setText(bundle.getString("method")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        pnlTop.add(lblMethod, gridBagConstraints);

        pnlMethodURI.setLayout(new BorderLayout(15, 0));

        cmdMethod.setModel(new DefaultComboBoxModel<>(new String[] { "GET", "POST", "DELETE", "PUT", "PATCH", "OPTIONS" }));
        pnlMethodURI.add(cmdMethod, BorderLayout.WEST);

        lblURI.setText("http://");
        pnlMethodURI.add(lblURI, BorderLayout.CENTER);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        pnlTop.add(pnlMethodURI, gridBagConstraints);

        lblPath.setText(bundle.getString("path")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        pnlTop.add(lblPath, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        pnlTop.add(txtPath, gridBagConstraints);

        btnHeaders.setText(bundle.getString("headers")); // NOI18N
        btnHeaders.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnHeadersActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 4;
        pnlTop.add(btnHeaders, gridBagConstraints);

        add(pnlTop, BorderLayout.NORTH);

        txtReqBody.setColumns(20);
        txtReqBody.setRows(5);
        spnReqBody.setViewportView(txtReqBody);

        tabBody.addTab(bundle.getString("requestBody"), spnReqBody); // NOI18N

        txtResBody.setEditable(false);
        txtResBody.setColumns(20);
        txtResBody.setRows(5);
        spnResBody.setViewportView(txtResBody);

        tabBody.addTab(bundle.getString("responseBody"), spnResBody); // NOI18N

        txtConsole.setEditable(false);
        txtConsole.setColumns(20);
        txtConsole.setRows(5);
        spnConsole.setViewportView(txtConsole);

        tabBody.addTab(bundle.getString("console"), spnConsole); // NOI18N

        add(tabBody, BorderLayout.CENTER);

        pnlFooter.setLayout(new GridBagLayout());

        lblStatusCode.setText(bundle.getString("statusCode")); // NOI18N
        pnlFooter.add(lblStatusCode, new GridBagConstraints());

        lblCode.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        pnlFooter.add(lblCode, gridBagConstraints);

        btnSend.setText(bundle.getString("send")); // NOI18N
        btnSend.setEnabled(false);
        btnSend.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        pnlFooter.add(btnSend, gridBagConstraints);

        btnSave.setText(bundle.getString("save")); // NOI18N
        btnSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlFooter.add(btnSave, new GridBagConstraints());

        add(pnlFooter, BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEndpointInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndpointInfoActionPerformed
        wizard.mainPanel.globalVarsDialog.openDialog();
        Amphibia.instance.resetEnvironmentModel();
    }//GEN-LAST:event_btnEndpointInfoActionPerformed

    private void cmdEndpointActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cmdEndpointActionPerformed
        if (cmdEndpoint.getSelectedIndex() > 1) {
            
        } else {
            
        }
    }//GEN-LAST:event_cmdEndpointActionPerformed

    private void btnHeadersActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnHeadersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHeadersActionPerformed

    private void btnSendActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSaveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmdInterfaceActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cmdInterfaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdInterfaceActionPerformed

    private void btnInterfaceInfoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnInterfaceInfoActionPerformed
        wizard.openInterfacePanel(this);
    }//GEN-LAST:event_btnInterfaceInfoActionPerformed

    private void cmdEndpointItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_cmdEndpointItemStateChanged
        btnSend.setEnabled(cmdEndpoint.getSelectedItem() != null);
        if (btnSend.isEnabled()) {
            lblURI.setText(cmdEndpoint.getSelectedItem().toString());
        } else {
            lblURI.setText("http://");
        }
    }//GEN-LAST:event_cmdEndpointItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton btnEndpointInfo;
    JButton btnHeaders;
    JButton btnInterfaceInfo;
    JButton btnSave;
    JButton btnSend;
    JComboBox<String> cmdEndpoint;
    JComboBox<String> cmdInterface;
    JComboBox<String> cmdMethod;
    JLabel lblCode;
    JLabel lblEndpoint;
    JLabel lblInterface;
    JLabel lblMethod;
    JLabel lblPath;
    JLabel lblStatusCode;
    JLabel lblURI;
    JPanel pnlEndpoint;
    JPanel pnlFooter;
    JPanel pnlInterface;
    JPanel pnlMethodURI;
    JPanel pnlTop;
    JScrollPane spnConsole;
    JScrollPane spnReqBody;
    JScrollPane spnResBody;
    JTabbedPane tabBody;
    JTextArea txtConsole;
    JTextField txtPath;
    JTextArea txtReqBody;
    JTextArea txtResBody;
    // End of variables declaration//GEN-END:variables
}
