/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinix.amphibia.components;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

/**
 *
 * @author dgofman
 */
public class Wizard extends javax.swing.JPanel {

    /**
     * Creates new form Wizard
     */
    public Wizard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabNav = new JTabbedPane();
        wizardTab = new WizardTab();

        setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        setLayout(new BorderLayout());

        tabNav.addTab("", new ImageIcon(getClass().getResource("/com/equinix/amphibia/icons/wizard_16.png")), wizardTab); // NOI18N

        add(tabNav, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JTabbedPane tabNav;
    WizardTab wizardTab;
    // End of variables declaration//GEN-END:variables
}
